msbuild /m Sample.Win81.sln /t:Build "/p:Configuration=Release;Platform=ARM"
msbuild /m Sample.Win81.sln /t:Build "/p:Configuration=Release;Platform=x86"
msbuild /m Sample.Win81.sln /t:Build "/p:Configuration=Release;Platform=x64"
msbuild /m Sample.Win81.sln /t:Build "/p:Configuration=Debug;Platform=ARM"
msbuild /m Sample.Win81.sln /t:Build "/p:Configuration=Debug;Platform=x86"
msbuild /m Sample.Win81.sln /t:Build "/p:Configuration=Debug;Platform=x64"

msbuild /m Samples.WP8.sln /t:Build "/p:Configuration=Release;Platform=x86"
msbuild /m Samples.WP8.sln /t:Build "/p:Configuration=Release;Platform=ARM"
msbuild /m Samples.WP8.sln /t:Build "/p:Configuration=Debug;Platform=x86"
msbuild /m Samples.WP8.sln /t:Build "/p:Configuration=Debug;Platform=ARM"
