md ..\Distribution\
md ..\Distribution\.nuget\

md ..\Distribution\App\
md ..\Distribution\App\WinRT\
md ..\Distribution\App\WinRT\HlsView.Win81\
md ..\Distribution\App\WinRT\HlsView.Win81\Assets\
md ..\Distribution\App\WinRT\HlsView.Win81\Properties\
md ..\Distribution\App\Silverlight\
md ..\Distribution\App\Silverlight\HlsView.Silverlight\
md ..\Distribution\App\Silverlight\HlsView.Silverlight\Properties\

md ..\Distribution\bin\
md ..\Distribution\bin\Debug\
md ..\Distribution\bin\Release\
md ..\Distribution\bin\Debug\WP7\
md ..\Distribution\bin\Debug\WP8\
md ..\Distribution\bin\Debug\WP8\ARM\
md ..\Distribution\bin\Debug\WP8\x86\
md ..\Distribution\bin\Debug\Silverlight\
md ..\Distribution\bin\Debug\WinRT\ARM\
md ..\Distribution\bin\Debug\WinRT\x86\
md ..\Distribution\bin\Debug\WinRT\x64\
md ..\Distribution\bin\Release\WP7\
md ..\Distribution\bin\Release\WP8\
md ..\Distribution\bin\Release\WP8\ARM\
md ..\Distribution\bin\Release\WP8\x86\
md ..\Distribution\bin\Release\Silverlight\
md ..\Distribution\bin\Release\WinRT\ARM\
md ..\Distribution\bin\Release\WinRT\x86\
md ..\Distribution\bin\Release\WinRT\x64\

md ..\Distribution\Global\

md ..\Distribution\Libraries\
md ..\Distribution\Libraries\SM.Media.BackgroundAudioStreamingAgent.WP7\
md ..\Distribution\Libraries\SM.Media.BackgroundAudioStreamingAgent.WP7\Properties\
md ..\Distribution\Libraries\SM.Media.BackgroundAudioStreamingAgent.WP8\
md ..\Distribution\Libraries\SM.Media.BackgroundAudioStreamingAgent.WP8\Properties\
md ..\Distribution\Libraries\SM.Media.Platform.WP7\
md ..\Distribution\Libraries\SM.Media.MediaPlayer.WP7\
md ..\Distribution\Libraries\SM.Media.MediaPlayer.WP7\Properties\
md ..\Distribution\Libraries\SM.Media.MediaPlayer.WP8\
md ..\Distribution\Libraries\SM.Media.MediaPlayer.WP8\Properties\

md ..\Distribution\Phone\
md ..\Distribution\Phone\BackgroundAudio.Sample.WP7\
md ..\Distribution\Phone\BackgroundAudio.Sample.WP7\Images\
md ..\Distribution\Phone\BackgroundAudio.Sample.WP7\Properties\
md ..\Distribution\Phone\BackgroundAudio.Sample.WP8\
md ..\Distribution\Phone\BackgroundAudio.Sample.WP8\Assets\
md ..\Distribution\Phone\BackgroundAudio.Sample.WP8\Assets\Tiles\
md ..\Distribution\Phone\BackgroundAudio.Sample.WP8\Images\
md ..\Distribution\Phone\BackgroundAudio.Sample.WP8\Properties\
md ..\Distribution\Phone\BackgroundAudio.Sample.WP8\Resources\
md ..\Distribution\Phone\HlsView\
md ..\Distribution\Phone\HlsView\Properties\
md ..\Distribution\Phone\HlsView.WP8\
md ..\Distribution\Phone\HlsView.WP8\Assets\
md ..\Distribution\Phone\HlsView.WP8\Assets\Tiles\
md ..\Distribution\Phone\HlsView.WP8\Properties\
md ..\Distribution\Phone\HlsView.WP8\Resources\
md ..\Distribution\Phone\SamplePlayer.WP7\
md ..\Distribution\Phone\SamplePlayer.WP7\Properties\
md ..\Distribution\Phone\SamplePlayer.WP8\
md ..\Distribution\Phone\SamplePlayer.WP8\Properties\
md ..\Distribution\Phone\SamplePlayer.WP8\Assets\
md ..\Distribution\Phone\SamplePlayer.WP8\Assets\Tiles\
md ..\Distribution\Phone\SamplePlayer.WP8\Resources\

md ..\Distribution\smf\
